<?php
use App\Core\Format;
$durationLabel=static function(?int $seconds): string{if($seconds===null)return 'Sem dados';if($seconds<60)return $seconds.' s';$m=(int)round($seconds/60);if($m<60)return $m.' min';$h=intdiv($m,60);$rm=$m%60;if($h<24)return $h.'h'.($rm?' '.$rm.'min':'');$d=intdiv($h,24);$rh=$h%24;return $d.'d'.($rh?' '.$rh.'h':'');};
$maxMonthly=1;foreach($monthly as$m)$maxMonthly=max($maxMonthly,$m['uploads'],$m['approvals'],$m['corrections'],$m['closures']);
?>
<div class="historical-page historical-macro-page">
<section class="historical-hero"><div><span class="historical-eyebrow">VISÃO MACRO STRATELLI</span><h1>Indicadores Executivos Históricos</h1><p>Comparativo histórico da carteira de municípios, com desempenho de fases, validações, correções e conclusão da etapa atual de cada município.</p></div><div class="historical-hero-actions"><form method="get" class="historical-period-form"><label>Período<select name="periodo" onchange="this.form.submit()"><?php foreach([6=>'Últimos 6 meses',12=>'Últimos 12 meses',24=>'Últimos 24 meses'] as$v=>$label):?><option value="<?=$v?>" <?=$months===$v?'selected':''?>><?=$label?></option><?php endforeach;?></select></label></form><a class="btn neutral" href="/admin/indicadores-historicos/exportar?periodo=<?=$months?>">↓ Exportar CSV</a></div></section>
<section class="historical-kpis macro">
<article class="historical-kpi"><small>MUNICÍPIOS NA CARTEIRA</small><strong><?=$summary['municipios']?></strong><span>Clientes cadastrados na plataforma</span></article>
<article class="historical-kpi"><small>TEMPO MÉDIO POR FASE</small><strong><?=$summary['avgPhaseDays']!==null?Format::h($summary['avgPhaseDays']).' dia(s)':'—'?></strong><span><?=$summary['closedPhaseCount']?> encerramento(s) analisado(s)</span></article>
<article class="historical-kpi"><small>VALIDAÇÃO STRATELLI</small><strong><?=Format::h($durationLabel($summary['avgValidationSeconds']))?></strong><span><?=$summary['validationCount']?> decisão(ões) documentais</span></article>
<article class="historical-kpi"><small>APROVAÇÃO NA 1ª ENTREGA</small><strong><?=$summary['firstPassRate']!==null?Format::h($summary['firstPassRate']).'%':'—'?></strong><span><?=$summary['firstPassApproved']?> de <?=$summary['firstPassTotal']?> primeiras versões</span></article>
<article class="historical-kpi"><small>FASES NO PRAZO</small><strong><?=$summary['phaseOnTimeRate']!==null?Format::h($summary['phaseOnTimeRate']).'%':'—'?></strong><span>Considerando encerramentos formais no período</span></article>
<article class="historical-kpi"><small>ETAPAS CONCLUÍDAS NO PRAZO</small><strong><?=$summary['etapasConcluidas']?($summary['etapasNoPrazo'].'/'.$summary['etapasConcluidas']):'—'?></strong><span><?=$summary['etapasNoPrazoRate']!==null?Format::h($summary['etapasNoPrazoRate']).'% das concluídas':'Ainda sem etapa concluída'?></span></article>
</section>

<div class="historical-two-columns macro-top">
<section class="card historical-section"><div class="historical-section-head"><div><h2>Fases com maior atraso médio</h2><p>Comparação entre municípios com encerramentos formais no período.</p></div></div><?php if($phaseRanking):?><div class="historical-ranking"><?php foreach(array_slice($phaseRanking,0,8) as$i=>$r):?><article><span class="historical-rank-number"><?=$i+1?></span><div><b><?=Format::h($r['label'])?></b><small><?=$r['count']?> encerramento(s) · <?=$r['onTimeRate']?>% no prazo</small></div><strong><?=($r['avgDelay']>0?'+':'').$r['avgDelay']?> d</strong></article><?php endforeach;?></div><?php else:?><div class="historical-empty">Ainda não existem encerramentos suficientes no período.</div><?php endif;?></section>
<section class="card historical-section"><div class="historical-section-head"><div><h2>Unidades com mais correções</h2><p>Ranking de Secretarias por cliente.</p></div><span class="historical-section-badge"><?=$summary['corrections']?> correção(ões)</span></div><?php if($secretariasCorrecoes):?><div class="historical-ranking corrections"><?php $maxCorrection=max(array_column($secretariasCorrecoes,'correcoes'))?:1;foreach($secretariasCorrecoes as$i=>$s):?><article><span class="historical-rank-number"><?=$i+1?></span><div class="historical-ranking-bar-wrap"><div><b><?=Format::h($s['label'])?></b><small><?=$s['documentos']?> documento(s) distinto(s)</small></div><div class="historical-ranking-bar"><span style="width:<?=round($s['correcoes']/$maxCorrection*100,2)?>%"></span></div></div><strong><?=$s['correcoes']?></strong></article><?php endforeach;?></div><?php else:?><div class="historical-empty">Nenhuma correção registrada no período.</div><?php endif;?></section>
</div>

<section class="card historical-section"><div class="historical-section-head"><div><h2>Desempenho histórico por município</h2><p>Resumo executivo da etapa atual de cada cliente.</p></div><span class="historical-section-badge"><?=count($clients)?> município(s)</span></div><div class="table-scroll"><table class="production-table historical-table"><thead><tr><th>Município</th><th>Etapa atual</th><th>Fases encerradas no período</th><th>Fases no prazo</th><th>Validação média</th><th>1ª entrega</th><th>Correções</th><th>Acesso</th></tr></thead><tbody><?php foreach($clients as$c):$status=$c['phase']['etapa']['status'];$class=$status==='done_on_time'?'success':($status==='done_late'?'danger':($status==='in_progress'?'warning':'neutral'));?><tr><td><b><?=Format::h($c['municipio']['nome'].' - '.$c['municipio']['uf'])?></b><br><small><?=Format::h($c['municipio']['status'])?></small></td><td><span class="historical-status <?=$class?>"><?=Format::h($c['phase']['etapa']['label'])?></span></td><td><?=$c['phase']['closedCount']?></td><td><?=$c['phase']['onTimeRate']!==null?Format::h($c['phase']['onTimeRate']).'%':'—'?></td><td><?=Format::h($durationLabel($c['docs']['avgValidationSeconds']))?></td><td><?=$c['docs']['firstPassRate']!==null?Format::h($c['docs']['firstPassRate']).'%':'—'?></td><td><?=$c['docs']['corrections']?></td><td><a class="mini-link primary" href="/<?=Format::h($c['municipio']['slug'])?>/relatorios/historicos?periodo=<?=$months?>">Abrir histórico</a></td></tr><?php endforeach;?></tbody></table></div></section>

<section class="card historical-section"><div class="historical-section-head"><div><h2>Evolução mensal da carteira</h2><p>Volume consolidado de entregas e decisões documentais em todos os clientes.</p></div><div class="historical-chart-legend"><span><i class="uploads"></i>Envios</span><span><i class="approvals"></i>Aprovações</span><span><i class="corrections"></i>Correções</span><span><i class="closures"></i>Fases encerradas</span></div></div><div class="historical-chart-scroll"><div class="historical-month-chart" style="--months:<?=count($monthly)?>"><?php foreach($monthly as$m):?><div class="historical-month"><div class="historical-bars"><span class="uploads" style="height:<?=max(2,round($m['uploads']/$maxMonthly*100,2))?>%"><b><?=$m['uploads']?></b></span><span class="approvals" style="height:<?=max(2,round($m['approvals']/$maxMonthly*100,2))?>%"><b><?=$m['approvals']?></b></span><span class="corrections" style="height:<?=max(2,round($m['corrections']/$maxMonthly*100,2))?>%"><b><?=$m['corrections']?></b></span><span class="closures" style="height:<?=max(2,round($m['closures']/$maxMonthly*100,2))?>%"><b><?=$m['closures']?></b></span></div><small><?=Format::h($m['label'])?></small></div><?php endforeach;?></div></div></section>
<section class="card historical-methodology"><div><span>i</span><div><h3>Escopo atual</h3><p>Esta versão mede historicamente a etapa atual configurada em cada município, sem antecipar a futura arquitetura de múltiplas etapas/processos simultâneos.</p></div></div><ul><?php foreach($methodology as$item):?><li><?=Format::h($item)?></li><?php endforeach;?></ul></section>
</div>
