<?php
namespace App\Controllers;
use App\Core\Auth;use App\Core\Csrf;use App\Core\Response;use App\Core\Router;use App\Core\Session;use App\Core\View;use App\Services\PasswordResetService;use App\Services\UserService;
final class AuthController
{
    public function loginForm(): void{View::render('auth/login',['erro'=>Session::pullFlash('erro'),'ok'=>Session::pullFlash('ok')],'guest');}
    public function login(): void{if(!Csrf::validate($_POST['_token']??null)){Session::flash('erro','Sessão expirada. Tente novamente.');Response::redirect('/login');}$email=trim((string)($_POST['email']??''));$senha=(string)($_POST['senha']??'');if(!Auth::attempt($email,$senha)){Session::flash('erro','E-mail ou senha inválidos, ou acesso temporariamente bloqueado por segurança.');Response::redirect('/login');}Response::redirect(Router::homeForUser());}
    public function changePasswordForm(): void{View::render('auth/change_password',['title'=>'Alterar senha','erro'=>Session::pullFlash('erro'),'ok'=>Session::pullFlash('ok')]);}
    public function changePassword(): void{if(!Csrf::validate($_POST['_token']??null)){Session::flash('erro','Sessão expirada. Tente novamente.');Response::redirect('/conta/senha');}try{(new UserService())->changeOwnPassword((int)Auth::id(),$_POST);Session::flash('ok','Senha alterada com sucesso.');}catch(\Throwable$e){Session::flash('erro',$e->getMessage());}Response::redirect('/conta/senha');}
    public function forgotForm(): void{View::render('auth/forgot_password',['erro'=>Session::pullFlash('erro'),'ok'=>Session::pullFlash('ok'),'reset_link'=>Session::pullFlash('reset_link')],'guest');}
    public function forgot(): void{if(!Csrf::validate($_POST['_token']??null)){Session::flash('erro','Sessão expirada. Tente novamente.');Response::redirect('/esqueci-senha');}try{$link=(new PasswordResetService())->request((string)($_POST['email']??''));Session::flash('ok','Se o e-mail estiver vinculado a uma conta ativa, enviaremos as instruções de recuperação. Verifique também a caixa de spam.');if($link)Session::flash('reset_link',$link);}catch(\Throwable){Session::flash('ok','Se o e-mail estiver vinculado a uma conta ativa, enviaremos as instruções de recuperação. Verifique também a caixa de spam.');}Response::redirect('/esqueci-senha');}
    public function resetForm(string $token): void{if(!(new PasswordResetService())->validate($token)){View::render('auth/reset_password',['title'=>'Redefinir senha','token'=>$token,'erro'=>'Link de recuperação inválido ou expirado.'],'guest');return;}View::render('auth/reset_password',['title'=>'Redefinir senha','token'=>$token,'erro'=>Session::pullFlash('erro')],'guest');}
    public function reset(string $token): void{if(!Csrf::validate($_POST['_token']??null)){Session::flash('erro','Sessão expirada. Tente novamente.');Response::redirect('/redefinir-senha/'.$token);}try{(new PasswordResetService())->reset($token,(string)($_POST['nova_senha']??''),(string)($_POST['confirmacao_senha']??''));Session::flash('ok','Senha redefinida. Faça login com a nova credencial.');Response::redirect('/login');}catch(\Throwable$e){Session::flash('erro',$e->getMessage());Response::redirect('/redefinir-senha/'.$token);}}
    public function logout(): void{if(Csrf::validate($_POST['_token']??null))Auth::logout();Response::redirect('/login');}
}
