<link rel="stylesheet" href="/assets/sla.css?v=4208">
<?php use App\Core\Csrf;use App\Core\Format;$slug=$tenant['slug'];$phase=$faseSituacional;$deadline=$prazoDashboard;$phaseStatus=match($faseSituacionalStatus){'done'=>'ENCERRADA','ready'=>'PRONTA PARA ENCERRAMENTO','correction'=>'CORREÇÃO SOLICITADA','run'=>'EM ANDAMENTO',default=>'AGUARDANDO INÍCIO'};?>
<div class="hero dashboard-hero"><div><h1>Dashboard Situacional</h1><p><?=$scope==='stratelli'?'Visão executiva do processo atual do município, da fase em andamento e das secretarias que ainda precisam agir.':($scope==='secretaria'?'Visão restrita às fases e aos documentos sob responsabilidade da sua secretaria.':'Visão consolidada do processo municipal, reunindo todas as secretarias, documentos, entregas, correções e análises.')?></p></div><div class="notice <?=$scope==='stratelli'?'purple':''?>">● Situação calculada em tempo real pelo banco de dados</div></div>
<?php $desk=$pendingDesk??['actionCount'=>0,'stats'=>[]];?>
<section class="workdesk-dashboard-strip <?=($desk['actionCount']??0)>0?'has-actions':'is-clear'?>"><div class="workdesk-dashboard-icon"><?=($desk['actionCount']??0)>0?'◆':'✓'?></div><div><small><?=$scope==='stratelli'?'CENTRAL DE PENDÊNCIAS':'MINHA MESA'?></small><b><?php if(($desk['actionCount']??0)>0):?>Você tem <?=$desk['actionCount']?> ação(ões) pendente(s)<?php else:?>Nenhuma ação imediata para o seu perfil<?php endif;?></b><span><?php if(($desk['actionCount']??0)>0):?><?=($desk['stats']['correction']??0)?> correção(ões) · <?=($desk['stats']['send']??0)?> envio(s) · <?=($scope==='stratelli'?($desk['stats']['validation']??0):($desk['stats']['waiting']??0))?> em análise<?php if(($desk['stats']['closure']??0)>0):?> · <?=($desk['stats']['closure']??0)?> encerramento(s)<?php endif;?><?php else:?>Acompanhe itens informativos e dependências quando necessário.<?php endif;?></span></div><a class="btn primary" href="/<?=Format::h($slug)?>/pendencias"><?=$scope==='stratelli'?'Abrir Central':'Abrir Minha Mesa'?></a></section>
<section class="card dashboard-schedule-anchor"><div><b>Marco inicial do cronograma</b><p>Os prazos usam a duração cadastrada no Gantt. Cada fase começa no dia seguinte à conclusão da anterior.</p></div><?php if($scope==='stratelli'):?><form method="post" action="/<?=Format::h($slug)?>/cronograma/inicio"><input type="hidden" name="_token" value="<?=Format::h(Csrf::token())?>"><label>Início do processo<input type="date" name="data_inicio" value="<?=Format::h($dataInicioProcesso)?>" required></label><button class="btn primary">Recalcular prazos</button></form><?php else:?><span class="deadline-status-pill scheduled">Processo iniciado em <?=Format::h(Format::date($dataInicioProcesso))?></span><?php endif;?></section>
<div class="kpis dashboard-kpis">
<div class="kpi alert"><small><?=$scope==='secretaria'?'FASE DA SUA UNIDADE':'FASE ATUAL'?></small><b>Fase <?=Format::h($phase['ordem']??'—')?></b><span><?=Format::h($phase['aba']??'Sem fase ativa')?></span></div>
<div class="kpi kpi-deadline deadline-<?=Format::h($deadline['status']??'blocked')?>"><small>SITUAÇÃO DO PRAZO</small><b class="responsive-kpi-value"><?=Format::h($deadline['rotulo']??'—')?></b><span><?=Format::h($deadline['texto']??'Cronograma indisponível')?></span></div>
<div class="kpi success"><small>PROGRESSO GERAL</small><b><?=$progresso?>%</b><span><?=$totalAprovados?> de <?=$totalDocs?> documentos aprovados</span></div>
<div class="kpi alert"><small>SECRETARIAS PENDENTES</small><b><?=count($dashboardSecretariasPendentes)?></b><span>Precisam entregar ou corrigir</span></div>
<div class="kpi alert"><small>DOCUMENTOS PENDENTES</small><b><?=$dashboardFaseNaoEntregues+$dashboardFaseCorrecoes?></b><span>Na fase atual</span></div>
<div class="kpi waiting"><small>AGUARDANDO ANÁLISE</small><b><?=$dashboardFaseAguardando?></b><span>Recebidos na fase atual</span></div>
</div>
<?php if($phase):?><section class="dashboard-phase-focus"><div class="dashboard-phase-number"><small>ESTAMOS ATUALMENTE NA</small><b><?=Format::h($phase['ordem'])?></b><span>FASE <?=Format::h($phase['ordem'])?><br><?=Format::h($phase['aba'])?></span></div><div class="dashboard-phase-main"><h2><?=Format::h($phase['titulo'])?></h2><p><?=Format::h($phase['descricao'])?></p><span class="phase-focus-status"><?=$phaseStatus?></span><div class="phase-focus-progress"><div><span>Progresso documental da fase</span><strong><?=$dashboardFaseProgresso?>%</strong></div><div class="phase-focus-track"><span style="width:<?=$dashboardFaseProgresso?>%"></span></div></div><div class="phase-focus-counters"><div><b><?=$dashboardFaseAprovados?></b><small>APROVADOS</small></div><div><b><?=$dashboardFaseAguardando?></b><small>EM ANÁLISE</small></div><div><b><?=$dashboardFaseCorrecoes?></b><small>CORREÇÕES</small></div><div><b><?=$dashboardFaseNaoEntregues?></b><small>NÃO ENTREGUES</small></div></div></div><div class="dashboard-phase-deadline"><b>Prazo da fase</b><p><?=Format::h(Format::date($deadline['inicio']??null))?> a <?=Format::h(Format::date($deadline['fim']??null))?></p><span class="deadline-status-pill <?=Format::h($deadline['status']??'blocked')?>"><?=Format::h($deadline['rotulo']??'—')?></span><p><?=Format::h($deadline['texto']??'')?></p><?php $canOpenDashboardPhase=(bool)($faseAcesso[(int)$phase['id']]['pode_acessar']??false);?><?php if($canOpenDashboardPhase):?><a class="btn primary" href="/<?=Format::h($slug)?>/workflow/fase/<?=(int)$phase['id']?>">Abrir detalhes da fase</a><?php else:?><span class="btn phase-locked-button" aria-disabled="true">🔒 Aguardando fase anterior</span><?php endif;?></div></section><?php endif;?>
<?php $slaRows=$slaOperacional['secretarias']??[];$slaResumo=$slaOperacional['resumo']??[];?>
<section class="sla-dashboard-strip">
    <div class="sla-dashboard-head"><div><h2><?=$scope==='secretaria'?'Meu SLA operacional':'SLA por Secretaria'?></h2><p>Pontualidade da primeira entrega obrigatória, correções e qualidade da primeira versão.</p></div><a class="mini-link primary" href="/<?=Format::h($slug)?>/relatorios/sla">Ver análise completa →</a></div>
    <?php if($slaRows):?><div class="sla-dashboard-list"><?php foreach(array_slice($slaRows,0,4) as $s):?><article class="sla-dashboard-item sla-tone-<?=Format::h($s['sla_class'])?>"><div class="sla-dashboard-item-top"><strong><?=Format::h($s['sigla']?:$s['nome'])?></strong><span><?=Format::h($s['sla_label'])?></span></div><b><?=$s['sla_percentual']===null?'—':Format::h(number_format((float)$s['sla_percentual'],1,',','.')).'%'?></b><small>dentro do prazo · <?=intval($s['correcoes'])?> correção(ões) · 1ª versão <?=$s['aprovacao_primeira_percentual']===null?'—':Format::h(number_format((float)$s['aprovacao_primeira_percentual'],0,',','.')).'%'?></small><div class="mini-bar"><span style="width:<?=max(0,min(100,(float)($s['sla_percentual']??0)))?>%"></span></div></article><?php endforeach;?></div><?php else:?><div class="delivery-secretaria-empty">O SLA será calculado automaticamente conforme as entregas e os prazos forem registrados.</div><?php endif;?>
</section>
<?php $previewMode='dashboard';require __DIR__.'/partials/process_preview.php';?>
<section class="card dashboard-actions"><div class="delivery-secretaria-head"><div><h2><?=$scope==='secretaria'?'Ações necessárias da sua secretaria':'Ações necessárias por secretaria'?></h2><p><?=$scope==='secretaria'?'Somente documentos sob responsabilidade da sua secretaria na fase atual.':'Veja quais secretarias ainda precisam enviar documentos ou atender às correções solicitadas nesta fase.'?></p></div><span class="delivery-secretaria-badge"><?=count($dashboardSecretariasPendentes)?> secretaria(s) com pendência</span></div>
<?php if($dashboardSecretariasPendentes):?><div class="delivery-secretaria-quickgrid"><?php foreach($dashboardSecretariasPendentes as$s):?><article class="delivery-secretaria-quickcard <?=Format::h($s['status_visual'])?>"><div class="delivery-secretaria-quickicon"><?=$s['nao_entregues']?'✕':'!'?></div><div class="delivery-secretaria-quickcontent"><div class="delivery-secretaria-quicktop"><strong><?=Format::h(($s['sigla']?$s['sigla'].' — ':'').$s['nome'])?></strong><span class="delivery-secretaria-quickpill"><?=$s['nao_entregues']?'ENVIO PENDENTE':'CORREÇÃO PENDENTE'?></span></div><div class="delivery-secretaria-quickmeta"><span>× <?=$s['nao_entregues']?> não entregue(s)</span><span>! <?=$s['correcoes']?> correção(ões)</span></div><?php if($s['documentos']):?><div class="delivery-secretaria-quickhint">Prioridade: <?=Format::h($s['documentos'][0]['nome'])?></div><?php endif;?></div></article><?php endforeach;?></div><?php else:?><div class="delivery-secretaria-empty">Nenhuma ação de envio ou correção pendente na fase atual.</div><?php endif;?></section>
<?php if($territorialEnabled??false):?>
<?php $hasTerritory=!empty($tenant['geojson_delimitacao']);$hasTerritorialMap=$hasTerritory||!empty($territorialObjects);$territorialMiniObjects=array_map(fn($o)=>['id'=>(int)$o['id'],'camada_id'=>(int)$o['camada_id'],'status'=>$o['status'],'geometry'=>json_decode((string)$o['geometria_geojson'],true)],$territorialObjects??[]);$territorialMiniLayers=array_map(fn($c)=>['id'=>(int)$c['id'],'cor'=>$c['cor'],'icone'=>$c['icone']],$territorialLayers??[]);?>
<section class="card dashboard-territory-card">
    <div class="dashboard-territory-copy">
        <div class="module-section-head compact"><div><h2>Inteligência Territorial</h2><p>Objetos geográficos e fases territorializadas desta instância.</p></div><a class="mini-link primary" href="/<?=Format::h($slug)?>/territorio">Abrir visão territorial</a></div>
        <div class="dashboard-territory-stats"><span><small>OBJETOS MAPEADOS</small><b><?=$territorialSummary['objetos']??0?></b></span><span><small>CAMADAS ATIVAS</small><b><?=$territorialSummary['camadas']??0?></b></span><span><small>FASES TERRITORIALIZADAS</small><b><?=$territorialSummary['processos_vinculados']??0?></b></span><span><small>ATENÇÃO / CRÍTICOS</small><b><?=($territorialSummary['atencao']??0)+($territorialSummary['criticos']??0)?></b></span></div>
    </div>
    <div class="dashboard-territory-visual">
        <?php if($hasTerritorialMap):?><div id="dashboardTerritoryMap" class="dashboard-territory-map"></div><?php else:?><div class="dashboard-territory-empty"><span>⌖</span><b>Sem inteligência territorial cadastrada</b><small>A Stratelli pode cadastrar camadas e objetos no módulo Território.</small></div><?php endif;?>
    </div>
</section>
<?php if($hasTerritorialMap):?>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="">
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
<script>
(function(){const el=document.getElementById('dashboardTerritoryMap');if(!el||typeof L==='undefined')return;const objects=<?=json_encode($territorialMiniObjects,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>,layers=<?=json_encode($territorialMiniLayers,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;const map=L.map(el,{zoomControl:false,attributionControl:false,scrollWheelZoom:false,dragging:false,doubleClickZoom:false,boxZoom:false,keyboard:false,touchZoom:false}).setView([<?=json_encode((float)($tenant['latitude']?:-15))?>,<?=json_encode((float)($tenant['longitude']?:-52))?>],10);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19}).addTo(map);const bounds=[];<?php if($hasTerritory):?>fetch('/media/municipios/<?=$tenant['id']?>/territorio',{credentials:'same-origin'}).then(r=>r.json()).then(geo=>{const boundary=L.geoJSON(geo,{style:{color:'#df4541',weight:2,fillColor:'#176fdd',fillOpacity:.07}}).addTo(map);const b=boundary.getBounds();if(b.isValid())map.fitBounds(b,{padding:[12,12]});}).catch(()=>{});<?php endif;?>const icons={pin:'📍',school:'▤',health:'✚',works:'◆',camera:'◉',area:'⬡'};const markerIcon=layer=>L.divIcon({className:'territorial-div-icon',html:`<span class="territorial-map-marker compact" style="--marker-color:${layer?.cor||'#176fdd'}"><span>${icons[layer?.icone]||icons.pin}</span></span>`,iconSize:[28,32],iconAnchor:[14,30]});objects.forEach(o=>{if(!o.geometry)return;const layer=layers.find(l=>l.id===o.camada_id),color=layer?.cor||'#176fdd';L.geoJSON({type:'Feature',properties:{},geometry:o.geometry},{style:{color,weight:3,fillColor:color,fillOpacity:.25},pointToLayer:(f,ll)=>L.marker(ll,{icon:markerIcon(layer),interactive:false})}).addTo(map)});setTimeout(()=>map.invalidateSize(),100);})();
</script>
<?php endif;?>
<?php endif;?>
<?php require __DIR__.'/partials/gantt.php';?>
