<?php
use App\Core\Format;
$durationLabel=static function(?int $seconds): string{if($seconds===null)return 'Sem dados';if($seconds<60)return $seconds.' s';$m=(int)round($seconds/60);if($m<60)return $m.' min';$h=intdiv($m,60);$rm=$m%60;if($h<24)return $h.'h'.($rm?' '.$rm.'min':'');$d=intdiv($h,24);$rh=$h%24;return $d.'d'.($rh?' '.$rh.'h':'');};
$maxMonthly=1;foreach($monthly as$m)$maxMonthly=max($maxMonthly,$m['uploads'],$m['approvals'],$m['corrections'],$m['closures']);
$stageName=$phase['stageName']??'Etapa 1';$etapaClass=match($phase['etapa']['status']){'done_on_time'=>'success','done_late'=>'danger','in_progress'=>'warning',default=>'neutral'};
?>
<div class="historical-page">
<section class="historical-hero"><div><span class="historical-eyebrow">INTELIGÊNCIA EXECUTIVA</span><h1>Indicadores Executivos Históricos</h1><p>Leitura de desempenho de <?=Format::h($stageName)?> baseada em encerramentos formais, versões documentais, validações e correções registradas na plataforma.</p></div><div class="historical-hero-actions"><form method="get" class="historical-period-form"><label>Período<select name="periodo" onchange="this.form.submit()"><?php foreach([6=>'Últimos 6 meses',12=>'Últimos 12 meses',24=>'Últimos 24 meses'] as$v=>$label):?><option value="<?=$v?>" <?=$months===$v?'selected':''?>><?=$label?></option><?php endforeach;?></select></label></form><a class="btn neutral" href="/<?=Format::h($tenant['slug'])?>/relatorios/historicos/exportar?periodo=<?=$months?>">↓ Exportar CSV</a><a class="btn neutral" href="/<?=Format::h($tenant['slug'])?>/relatorios">← Relatórios</a></div></section>

<section class="historical-kpis">
<article class="historical-kpi"><small>TEMPO MÉDIO POR FASE</small><strong><?=$phase['avgDays']!==null?Format::h($phase['avgDays']).' dia(s)':'—'?></strong><span><?=$phase['closedCount']?> fase(s) encerrada(s) no período</span></article>
<article class="historical-kpi <?=$phase['avgDelay']!==null&&$phase['avgDelay']>0?'is-alert':''?>"><small>ATRASO MÉDIO</small><strong><?=$phase['avgDelay']!==null?Format::h($phase['avgDelay']).' dia(s)':'—'?></strong><span>Comparação com a data limite recalculada</span></article>
<article class="historical-kpi"><small>VALIDAÇÃO STRATELLI</small><strong><?=Format::h($durationLabel($docs['avgValidationSeconds']))?></strong><span><?=$docs['validationCount']?> decisão(ões) analisada(s)</span></article>
<article class="historical-kpi"><small>APROVAÇÃO NA 1ª ENTREGA</small><strong><?=$docs['firstPassRate']!==null?Format::h($docs['firstPassRate']).'%':'—'?></strong><span><?=$docs['firstPassApproved']?> de <?=$docs['firstPassTotal']?> primeira(s) versão(ões)</span></article>
<article class="historical-kpi"><small>FASES ENCERRADAS NO PRAZO</small><strong><?=$phase['onTimeRate']!==null?Format::h($phase['onTimeRate']).'%':'—'?></strong><span><?=$phase['onTimeCount']?> de <?=$phase['closedCount']?> no período</span></article>
<article class="historical-kpi is-<?=$etapaClass?>"><small>SITUAÇÃO DE <?=Format::h(strtoupper($stageName))?></small><strong><?=Format::h($phase['etapa']['label'])?></strong><span><?php if($phase['etapa']['delay']!==null&&$phase['etapa']['delay']>0):?><?=Format::h($phase['etapa']['delay'])?> dia(s) além do prazo final<?php elseif($phase['etapa']['status']==='done_on_time'):?>Encerramento final dentro do cronograma operacional<?php else:?>Andamento conforme as fases formalmente encerradas<?php endif;?></span></article>
</section>

<section class="card historical-section"><div class="historical-section-head"><div><h2>Tempo e prazo por fase</h2><p>Acompanhamento histórico de cada fase visível neste perfil, considerando o encerramento formal vigente.</p></div><span class="historical-section-badge"><?=$phase['closedCount']?> encerrada(s) no período</span></div>
<div class="table-scroll"><table class="production-table historical-table"><thead><tr><th>Fase</th><th>Início operacional</th><th>Prazo limite</th><th>Encerramento</th><th>Planejado</th><th>Real</th><th>Desvio</th><th>Situação</th></tr></thead><tbody><?php if($phase['rows']):foreach($phase['rows'] as$r):$delay=$r['delay'];?><tr><td><b><?=Format::h($r['label'])?></b><br><small><?=Format::h($r['titulo'])?></small></td><td><?=Format::h(Format::date($r['start']))?></td><td><?=Format::h(Format::date($r['deadline']))?></td><td><?=Format::h(Format::date($r['closure']))?></td><td><?=$r['plannedDays']?> dia(s)</td><td><?=$r['actualDays']!==null?$r['actualDays'].' dia(s)':'—'?></td><td><?php if($delay===null):?>—<?php elseif($delay>0):?><span class="historical-delay late">+<?=$delay?> dia(s)</span><?php elseif($delay<0):?><span class="historical-delay early"><?=$delay?> dia(s)</span><?php else:?><span class="historical-delay ontime">0 dia</span><?php endif;?></td><td><span class="historical-status <?=$r['closed']?($r['onTime']?'success':'danger'):'neutral'?>"><?=Format::h($r['statusLabel'])?></span></td></tr><?php endforeach;else:?><tr><td colspan="8">Nenhuma fase disponível para o perfil.</td></tr><?php endif;?></tbody></table></div></section>

<div class="historical-two-columns">
<section class="card historical-section"><div class="historical-section-head"><div><h2>Fases que mais atrasam</h2><p>Ranking das fases encerradas com desvio positivo no período selecionado.</p></div></div><?php if($phase['delayedRanking']):?><div class="historical-ranking"><?php foreach(array_slice($phase['delayedRanking'],0,8) as$i=>$r):?><article><span class="historical-rank-number"><?=$i+1?></span><div><b><?=Format::h($r['label'])?></b><small>Prazo <?=Format::h(Format::date($r['deadline']))?> · encerrada em <?=Format::h(Format::date($r['closure']))?></small></div><strong>+<?=$r['delay']?> dia(s)</strong></article><?php endforeach;?></div><?php else:?><div class="historical-empty">Nenhuma fase encerrada com atraso neste período.</div><?php endif;?></section>
<section class="card historical-section"><div class="historical-section-head"><div><h2>Secretarias com mais correções</h2><p>Volume histórico de solicitações de correção em documentos municipais.</p></div><span class="historical-section-badge"><?=$docs['corrections']?> correção(ões)</span></div><?php if($secretariasCorrecoes):?><div class="historical-ranking corrections"><?php $maxCorrection=max(array_column($secretariasCorrecoes,'correcoes'))?:1;foreach($secretariasCorrecoes as$i=>$s):?><article><span class="historical-rank-number"><?=$i+1?></span><div class="historical-ranking-bar-wrap"><div><b><?=Format::h($s['label'])?></b><small><?=$s['documentos']?> documento(s) distinto(s)</small></div><div class="historical-ranking-bar"><span style="width:<?=round($s['correcoes']/$maxCorrection*100,2)?>%"></span></div></div><strong><?=$s['correcoes']?></strong></article><?php endforeach;?></div><?php else:?><div class="historical-empty">Nenhuma correção registrada no período.</div><?php endif;?></section>
</div>

<section class="card historical-section"><div class="historical-section-head"><div><h2>Evolução mensal</h2><p>Movimentação mensal de envios, aprovações, correções e encerramentos formais.</p></div><div class="historical-chart-legend"><span><i class="uploads"></i>Envios</span><span><i class="approvals"></i>Aprovações</span><span><i class="corrections"></i>Correções</span><?php if($scope!=='secretaria'):?><span><i class="closures"></i>Fases encerradas</span><?php endif;?></div></div>
<div class="historical-chart-scroll"><div class="historical-month-chart" style="--months:<?=count($monthly)?>"><?php foreach($monthly as$m):?><div class="historical-month"><div class="historical-bars"><span class="uploads" style="height:<?=max(2,round($m['uploads']/$maxMonthly*100,2))?>%" title="<?=$m['uploads']?> envio(s)"><b><?=$m['uploads']?></b></span><span class="approvals" style="height:<?=max(2,round($m['approvals']/$maxMonthly*100,2))?>%" title="<?=$m['approvals']?> aprovação(ões)"><b><?=$m['approvals']?></b></span><span class="corrections" style="height:<?=max(2,round($m['corrections']/$maxMonthly*100,2))?>%" title="<?=$m['corrections']?> correção(ões)"><b><?=$m['corrections']?></b></span><?php if($scope!=='secretaria'):?><span class="closures" style="height:<?=max(2,round($m['closures']/$maxMonthly*100,2))?>%" title="<?=$m['closures']?> fase(s) encerrada(s)"><b><?=$m['closures']?></b></span><?php endif;?></div><small><?=Format::h($m['label'])?></small></div><?php endforeach;?></div></div></section>

<section class="card historical-methodology"><div><span>i</span><div><h3>Como ler estes indicadores</h3><p>Os números são calculados exclusivamente a partir dos registros auditados existentes na plataforma.</p></div></div><ul><?php foreach($methodology as$item):?><li><?=Format::h($item)?></li><?php endforeach;?></ul></section>
</div>
