<link rel="stylesheet" href="/assets/structure-import.css?v=42014">
<?php
use App\Core\Auth;use App\Core\Csrf;use App\Core\Format;
$slug=$tenant['slug'];$isPlatform=Auth::isPlatformAdmin();$deadline=$prazoAtividade;$today=date('Y-m-d');$parametrosInstancia=$parametrosInstancia??[];$obsEnvioObrigatoria=!empty($parametrosInstancia['observacao_envio_obrigatoria']);$obsAprovacaoObrigatoria=!empty($parametrosInstancia['observacao_aprovacao_obrigatoria']);$obsEncerramentoObrigatoria=!empty($parametrosInstancia['observacao_encerramento_obrigatoria']);$obsReaberturaObrigatoria=!empty($parametrosInstancia['observacao_reabertura_obrigatoria']);
?>
<div class="hero"><div><h1>Workflow de Contratação / Fases</h1><p>Envio dos documentos e acompanhamento do processo</p></div><div class="notice <?=$scope==='stratelli'?'purple':''?>"><?=$scope==='municipio'?'Como Gestor Municipal, você acompanha e envia documentos de todas as secretarias vinculadas ao processo.':($scope==='secretaria'?'Acesso restrito aos documentos de responsabilidade de '.Format::h($user['secretaria_nome']??'sua secretaria').'. A fase atual é única para todas as secretarias e segue o andamento global definido pela Stratelli.':'Todas as fases, secretarias, tipos e modelos podem ser administrados no menu Configurações.')?></div></div>

<?php if(!$atividadePodeAcessar):?>
<section class="phase-access-locked"><div class="phase-access-locked-icon">🔒</div><div><h2>Próxima fase ainda bloqueada</h2><p><?=Format::h($scope==='secretaria'?'Você visualiza somente as fases em que sua secretaria ou departamento possui documentos atribuídos. A próxima fase da sua unidade será liberada quando todas as fases anteriores estiverem formalmente encerradas pela Stratelli.':'As próximas fases permanecem visíveis para acompanhamento, mas só podem ser abertas quando a fase anterior estiver formalmente encerrada.')?></p></div><div class="phase-access-locked-meta"><span>Acesso sequencial</span><b><?=Format::h($atividade?$atividade['aba']:'Aguardando liberação')?></b></div></section>
<?php $previewMode='workflow';require __DIR__.'/partials/process_preview.php';?>
<?php elseif($scope==='secretaria'&&!$secretariaTemDocumentosFaseAtual):?>
<section class="secretaria-no-documents"><div class="secretaria-no-documents-icon">✓</div><div><h2>Nenhum documento atribuído à sua unidade nesta fase</h2><p>Esta fase está liberada, porém não existem documentos ativos vinculados à sua secretaria ou departamento.</p></div><div class="secretaria-no-documents-meta"><span>Sem ação necessária</span><b>Andamento controlado pela Stratelli</b></div></section>
<?php else:?>
<div class="kpis workflow-kpis <?=$scope==='secretaria'?'secretaria':''?>">
<?php if($scope==='secretaria'):?>
<div class="kpi waiting"><small>DOCUMENTOS ENVIADOS</small><b><?=$workflowCounts['enviados']?></b><span>Enviados nesta fase pela secretaria</span></div><div class="kpi waiting"><small>AGUARDANDO VALIDAÇÃO</small><b><?=$workflowCounts['aguardando']?></b><span>Em análise pela Stratelli</span></div><div class="kpi alert"><small>DOCUMENTOS PENDENTES</small><b><?=$workflowCounts['pendentes']?></b><span>Aguardando envio</span></div><div class="kpi warning"><small>CORREÇÕES SOLICITADAS</small><b><?=$workflowCounts['correcoes']?></b><span>Pendências de correção</span></div><div class="kpi kpi-deadline deadline-<?=Format::h($deadline['status']??'blocked')?>"><small>PRAZO DA FASE</small><b><?=Format::h($deadline['rotulo']??'—')?></b><span><?=Format::h($deadline['texto']??'Cronograma indisponível')?></span></div>
<?php else:?>
<div class="kpi success"><small>PROGRESSO GERAL</small><b><?=$progresso?>%</b><span>Documentos aprovados</span></div><div class="kpi waiting"><small>DOCUMENTOS ENVIADOS</small><b><?=$totalEnviados?></b><span>Arquivos enviados</span></div><div class="kpi alert"><small>DOCUMENTOS PENDENTES</small><b><?=max(0,$totalDocs-$totalEnviados)?></b><span>Aguardando envio</span></div><div class="kpi waiting"><small>AGUARDANDO VALIDAÇÃO</small><b><?=$aguardando?></b><span>Em análise pela Stratelli</span></div><div class="kpi warning"><small>CORREÇÕES SOLICITADAS</small><b><?=$totalCorrecoes?></b><span>Pendências de correção</span></div><div class="kpi kpi-deadline deadline-<?=Format::h($deadline['status']??'blocked')?>"><small>PRAZO DA FASE</small><b><?=Format::h($deadline['rotulo']??'—')?></b><span><?=Format::h($deadline['texto']??'Cronograma indisponível')?></span></div><?php if($scope==='stratelli'):?><div class="kpi success"><small>FASES ENCERRADAS</small><b><?=$dashboardFasesConcluidas?> de <?=$dashboardQtdFases?></b><span>Fases encerradas formalmente</span></div><div class="kpi alert"><small>SECRETARIAS PENDENTES</small><b><?=count($dashboardSecretariasPendentes)?></b><span>Com ações na fase atual</span></div><?php endif;?>
<?php endif;?></div>

<?php $previewMode='workflow';require __DIR__.'/partials/process_preview.php';?>

<?php $archive=$etapaArquivamento??[]; if(!empty($archive['arquivada'])): $ar=$archive['registro']??[]; ?>
<section class="stage-archive-banner archived">
    <div class="stage-archive-icon">✓</div>
    <div class="stage-archive-copy"><span>ETAPA 1</span><h2>Encerrada e arquivada</h2><p>O processo foi encerrado formalmente e o pacote de encerramento foi preservado com fases, documentos, versões, hashes, responsáveis, aprovações, encerramentos e histórico. A instância está em modo somente leitura para preservar a cadeia de custódia.</p><small>Pacote #<?=intval($ar['id']??0)?> · SHA-256 <?=Format::h($ar['checksum_sha256']??'')?> · <?=Format::h(Format::dateTime($ar['arquivado_em']??null))?></small></div>
    <?php if($isPlatform):?><a class="btn tiny secondary" href="/<?=Format::h($slug)?>/etapa-1/arquivamento/download">↓ Exportar pacote</a><?php endif; ?>
</section>
<?php elseif($scope==='stratelli' && !empty($archive['pode_arquivar'])): ?>
<section class="stage-archive-banner ready">
    <div class="stage-archive-icon">◆</div>
    <div class="stage-archive-copy"><span>ETAPA 1 · PRONTA PARA ENCERRAMENTO</span><h2>Todos os documentos e todas as fases estão concluídos</h2><p>O próximo passo é gerar o pacote oficial de encerramento. Depois do arquivamento, a Etapa 1 ficará em modo somente leitura e o pacote passará a ser a referência formal do estado encerrado.</p><small><?=$archive['fases_encerradas']?> de <?=$archive['total_fases']?> fases encerradas formalmente.</small></div>
    <form method="post" action="/<?=Format::h($slug)?>/etapa-1/arquivar" onsubmit="return confirm('Encerrar e arquivar a Etapa 1? Depois desta operação a instância ficará em modo somente leitura e o pacote de encerramento será preservado.');"><input type="hidden" name="_token" value="<?=Format::h(Csrf::token())?>"><button class="btn primary" type="submit">✓ Encerrar e arquivar Etapa 1</button></form>
</section>
<?php elseif($scope==='stratelli' && !empty($archive['total_fases'])): ?>
<section class="stage-archive-banner pending">
    <div class="stage-archive-icon">◷</div>
    <div class="stage-archive-copy"><span>ETAPA 1</span><h2>Encerramento ainda não liberado</h2><p>O pacote só pode ser gerado depois que todas as fases ativas forem formalmente encerradas.</p><small><?=$archive['fases_encerradas']?> de <?=$archive['total_fases']?> fases encerradas.</small></div>
</section>
<?php endif; ?>

<?php if($scope==='secretaria'&&$secretariaTemDocumentosFaseAtual&&$summary['total']):?>
<section class="card workflow-inline-progress"><div class="workflow-inline-progress-head"><div><strong>Andamento dos documentos da sua secretaria na fase atual</strong><br><small>Visualização rápida do percentual aprovado, aguardando validação, em correção e não entregue.</small></div><span class="workflow-inline-progress-pill">Fase <?=Format::h($atividade['ordem'])?> · <?=Format::h($atividade['aba'])?></span></div>
<div class="delivery-progress-bar"><?php if($summary['delivered']):?><span class="delivered" style="width:<?=number_format($summary['percent_delivered'],4,'.','')?>%"><b><?=round($summary['percent_delivered'])?>%</b></span><?php endif;?><?php if($summary['awaiting_validation']):?><span class="awaiting-validation" style="width:<?=number_format($summary['percent_waiting'],4,'.','')?>%"><b><?=round($summary['percent_waiting'])?>%</b></span><?php endif;?><?php if($summary['needs_correction']):?><span class="needs-correction" style="width:<?=number_format($summary['percent_correction'],4,'.','')?>%"><b><?=round($summary['percent_correction'])?>%</b></span><?php endif;?><?php if($summary['not_delivered']):?><span class="not-delivered" style="width:<?=number_format($summary['percent_pending'],4,'.','')?>%"><b><?=round($summary['percent_pending'])?>%</b></span><?php endif;?></div><div class="delivery-legend"><span><i class="delivered"></i>Verde: entregue e aprovado</span><span><i class="awaiting-validation"></i>Azul: aguardando validação</span><span><i class="needs-correction"></i>Amarelo: correção necessária</span><span><i class="not-delivered"></i>Vermelho: ainda não entregue</span></div></section>
<?php endif;?>

<?php if($atividade&&$atividadePodeAcessar):?>
<div class="content workflow-content">
<section class="card phase-summary <?=Format::h($faseVisualClass)?>"><div class="phase-summary-head"><h2>Fase <?=Format::h($atividade['ordem'])?> - <?=Format::h($atividade['titulo'])?></h2><span class="statusbox <?=Format::h($faseVisualClass)?>"><?=Format::h($faseStatusLabel)?></span></div><p><?=Format::h($atividade['descricao'])?></p><div class="details-row"><div class="detail <?=$scope==='secretaria'?'deadline-'.Format::h($workflowPrazoEntregaClasse):''?>"><small><?=$scope==='secretaria'?'Prazo para entrega':'Prazo'?></small><?php if($scope==='secretaria'):?><b><?=Format::h($workflowPrazoEntregaTexto)?></b><?php if($workflowPrazoEntregaComplemento):?><span class="detail-note"><?=Format::h($workflowPrazoEntregaComplemento)?></span><?php endif;?><?php else:?><b>Dia <?=Format::h($atividade['dia_inicio'])?> ao <?=Format::h($atividade['dia_fim'])?></b><?php endif;?></div><div class="detail"><small>Responsável</small><b><?=Format::h($atividade['responsavel'])?></b></div><div class="detail"><small>Duração</small><b><?=max(1,(int)$atividade['dia_fim']-(int)$atividade['dia_inicio']+1)?> dia(s)</b></div><div class="detail"><small>Entregável</small><b><?=Format::h($atividade['entregavel'])?></b></div></div></section>

<section class="card deadline-control-card <?=Format::h($deadline['status']??'blocked')?>"><div class="deadline-control-head"><div><h2>Controle de prazo da Fase <?=Format::h($atividade['ordem'])?></h2><p>O prazo utiliza os <?=Format::h($deadline['duracao']??1)?> dia(s) cadastrados no Gantt e começa no dia seguinte ao encerramento formal da fase anterior.</p></div><span class="deadline-status-pill <?=Format::h($deadline['status']??'blocked')?>"><?=Format::h($deadline['rotulo']??'—')?></span></div><div class="deadline-control-grid"><div class="deadline-control-item"><small>Início do processo</small><b><?=Format::h(Format::date($dataInicioProcesso))?></b></div><div class="deadline-control-item"><small>Início desta fase</small><b><?=Format::h(Format::date($deadline['inicio']??null))?></b></div><div class="deadline-control-item"><small>Data limite</small><b><?=Format::h(Format::date($deadline['fim']??null))?></b></div><div class="deadline-control-item"><small>Encerramento formal</small><b><?=Format::h(Format::date($deadline['conclusao_real']??null))?></b></div><div class="deadline-control-item"><small>Situação</small><b><?=Format::h($deadline['texto']??'—')?></b></div></div><?php if(!empty($deadline['provisorio'])):?><span class="deadline-provisional">Datas provisórias: a fase anterior ainda não foi encerrada formalmente.</span><?php endif;?><div class="deadline-control-progress"><div class="deadline-time-head"><span>Prazo consumido até <?=Format::h(Format::date($today))?></span><strong><?=Format::h($deadline['percentual_tempo']??0)?>%</strong></div><div class="deadline-time-track <?=Format::h($deadline['status']??'blocked')?>"><span style="width:<?=Format::h($deadline['percentual_tempo']??0)?>%"></span><em><?=Format::h($deadline['percentual_tempo']??0)?>%</em></div></div>
<?php if($isPlatform):?><div class="deadline-control-actions phase-start-only"><form method="post" action="/<?=Format::h($slug)?>/cronograma/inicio"><input type="hidden" name="_token" value="<?=Format::h(Csrf::token())?>"><input type="hidden" name="fase_id" value="<?=$atividade['id']?>"><label>Marco inicial do processo<input type="date" name="data_inicio" value="<?=Format::h($dataInicioProcesso)?>" required></label><button class="btn neutral">Atualizar início</button></form></div><?php endif;?></section>

<section id="governanca-fase" class="card phase-formal-control <?=$faseFormalmenteEncerrada?'is-closed':($faseElegivelEncerramento?'is-ready':'is-pending')?>">
<div class="phase-formal-head"><div><small>GOVERNANÇA DA FASE</small><h2><?=$faseFormalmenteEncerrada?'Fase formalmente encerrada':($faseElegivelEncerramento?'Fase pronta para encerramento formal':'Encerramento formal da fase')?></h2><p><?=$faseFormalmenteEncerrada?'O conteúdo documental desta fase está bloqueado. Alterações exigem reabertura auditada.':($faseElegivelEncerramento?'Os documentos obrigatórios atingiram 100% de aprovação. A fase permanece atual até o encerramento formal pela Stratelli.':'O encerramento só será liberado quando todos os documentos obrigatórios estiverem aprovados.')?></p></div><span class="phase-formal-badge"><?=$faseFormalmenteEncerrada?'ENCERRADA':($faseElegivelEncerramento?'100% DOCUMENTAL':'AGUARDANDO DOCUMENTOS')?></span></div>
<?php if($faseFormalmenteEncerrada):?>
<div class="phase-formal-summary"><div><small>DATA DE ENCERRAMENTO</small><b><?=Format::h(Format::date($faseFechamento['data_conclusao_real']??null))?></b></div><div><small>RESPONSÁVEL</small><b><?=Format::h($faseFechamento['concluido_por_nome']??'Stratelli')?></b></div><div><small>REGISTRADO EM</small><b><?=Format::h(Format::dateTime($faseFechamento['encerrado_em']??$faseFechamento['atualizado_em']??null))?></b></div><div><small>SNAPSHOT SHA-256</small><b class="phase-snapshot-hash"><?=Format::h(!empty($faseFechamento['snapshot_sha256'])?substr($faseFechamento['snapshot_sha256'],0,16).'…':'Legado sem snapshot')?></b></div></div>
<?php if(!empty($faseFechamento['observacao'])):?><div class="phase-formal-note"><b>Observação do encerramento</b><p><?=nl2br(Format::h($faseFechamento['observacao']))?></p></div><?php endif;?>
<?php if($faseSnapshot):?><details class="phase-snapshot-details"><summary>Ver snapshot documental preservado</summary><div class="phase-snapshot-meta"><span><?=count($faseSnapshot['documentos']??[])?> documento(s) registrados</span><span>Gerado em <?=Format::h(Format::dateTime($faseSnapshot['gerado_em']??null))?></span><code>SHA-256 <?=Format::h($faseFechamento['snapshot_sha256']??'')?></code></div><div class="table-scroll"><table class="phase-snapshot-table"><thead><tr><th>Documento</th><th>Unidade</th><th>Versão</th><th>Status</th><th>Hash</th></tr></thead><tbody><?php foreach(($faseSnapshot['documentos']??[]) as$sd):?><tr><td><b><?=Format::h($sd['documento']??'—')?></b><?php if(empty($sd['obrigatorio'])):?><br><small>Opcional</small><?php endif;?></td><td><?=Format::h($sd['secretaria']??'—')?><?php if(!empty($sd['departamento'])):?><br><small><?=Format::h($sd['departamento'])?></small><?php endif;?></td><td><?=Format::h($sd['versao']??'—')?></td><td><?=Format::h($sd['status']??'PENDENTE')?></td><td><code><?=Format::h(!empty($sd['checksum_sha256'])?substr($sd['checksum_sha256'],0,12).'…':'—')?></code></td></tr><?php endforeach;?></tbody></table></div></details><?php endif;?>
<?php if($isPlatform):?><form class="phase-reopen-form" method="post" action="/<?=Format::h($slug)?>/cronograma/fases/<?=$atividade['id']?>/reabrir"><input type="hidden" name="_token" value="<?=Format::h(Csrf::token())?>"><input type="hidden" name="fase_id" value="<?=$atividade['id']?>"><label>Motivo da reabertura <span><?=$obsReaberturaObrigatoria?'obrigatório':'opcional'?></span><textarea name="motivo_reabertura" rows="2" maxlength="1000" <?=$obsReaberturaObrigatoria?'required':''?> placeholder="Explique por que a fase precisa ser reaberta e quais alterações serão realizadas."></textarea></label><button class="btn correct" type="submit">↺ Reabrir fase</button></form><?php endif;?>
<?php else:?>
<div class="phase-formal-readiness"><div><strong><?=$faseElegibilidade['approved']?> / <?=$faseElegibilidade['total']?></strong><span>documentos obrigatórios aprovados</span></div><div><strong><?=$faseElegibilidade['waiting']?></strong><span>aguardando validação</span></div><div><strong><?=$faseElegibilidade['correction']?></strong><span>em correção</span></div><div><strong><?=$faseElegibilidade['missing']?></strong><span>não enviados</span></div></div>
<?php if($faseElegivelEncerramento):?><?php if($isPlatform):?><?php $closureMinDate=(string)($deadline['inicio']??$dataInicioProcesso);$closureDateAvailable=$closureMinDate<=$today;?><?php if($closureDateAvailable):?><form class="phase-close-form" method="post" action="/<?=Format::h($slug)?>/cronograma/fases/<?=$atividade['id']?>/encerrar"><input type="hidden" name="_token" value="<?=Format::h(Csrf::token())?>"><input type="hidden" name="fase_id" value="<?=$atividade['id']?>"><label>Data do encerramento<input type="date" name="data_conclusao" value="<?=Format::h($today)?>" min="<?=Format::h($closureMinDate)?>" max="<?=Format::h($today)?>" required></label><label>Responsável<input type="text" value="<?=Format::h($user['nome']??'Stratelli')?>" readonly></label><label class="phase-close-observation">Observação do encerramento <span><?=$obsEncerramentoObrigatoria?'obrigatória':'opcional'?></span><textarea name="observacao" rows="2" maxlength="1000" <?=$obsEncerramentoObrigatoria?'required':''?> placeholder="Registre a decisão, conferências realizadas ou contexto do encerramento."></textarea></label><button class="btn approve" type="submit">✓ Confirmar encerramento formal</button></form><?php else:?><div class="phase-formal-waiting"><span>◷</span><div><b>Documentação pronta, aguardando início operacional</b><p>O encerramento formal poderá ser registrado a partir de <?=Format::h(Format::date($closureMinDate))?>, conforme o cronograma da fase.</p></div></div><?php endif;?><?php else:?><div class="phase-formal-waiting"><span>◎</span><div><b>Documentação concluída</b><p>A fase aguarda o encerramento formal pela Stratelli. Até esse ato, a próxima fase permanece bloqueada.</p></div></div><?php endif;?><?php endif;?>
<?php endif;?>
<?php if($faseHistoricoFormal):?><details class="phase-formal-history"><summary>Histórico formal da fase · <?=count($faseHistoricoFormal)?> evento(s)</summary><div class="phase-formal-history-list"><?php foreach($faseHistoricoFormal as$hf):?><article class="<?=$hf['evento']==='REABERTURA'?'reopen':'close'?>"><span><?=$hf['evento']==='REABERTURA'?'↺':'✓'?></span><div><b><?=$hf['evento']==='REABERTURA'?'Fase reaberta':'Fase encerrada'?></b><small><?=Format::h(Format::dateTime($hf['criado_em']))?> · <?=Format::h($hf['usuario_nome']??'Sistema')?></small><?php if(!empty($hf['observacao'])):?><p><?=Format::h($hf['observacao'])?></p><?php endif;?><?php if(!empty($hf['snapshot_sha256'])):?><code>Snapshot <?=Format::h(substr($hf['snapshot_sha256'],0,16))?>…</code><?php endif;?></div></article><?php endforeach;?></div></details><?php endif;?>
</section>

<section class="card grouped-documents-section"><h2>Documentos da Fase</h2><p><?=$scope==='secretaria'?'Os documentos estão organizados no agrupamento da sua secretaria, com entrega, modelo e informações próprias.':'Os documentos estão organizados por secretaria. Cada agrupamento preserva entrega, modelo, validação e histórico individualizados.'?></p>
<?php if(!$gruposDocumentosFase):?><div class="empty-state">Nenhum documento ativo foi configurado para esta fase.</div><?php else:$bySecretary=[];foreach($gruposDocumentosFase as$g){foreach($g['entregas']as$e){$r=$e['requisito'];$k='s'.$r['secretaria_id'];if(!isset($bySecretary[$k]))$bySecretary[$k]=['nome'=>$r['secretaria_nome'],'sigla'=>$r['secretaria_sigla'],'items'=>[]];$bySecretary[$k]['items'][]=['group'=>$g,'delivery'=>$e];}}?>
<div class="secretaria-doc-groups"><?php foreach($bySecretary as$sec):?><section class="secretaria-doc-group"><div class="secretaria-doc-group-head"><div><h3><?=Format::h(($sec['sigla']?$sec['sigla'].' — ':'').$sec['nome'])?></h3><p>Entregas, modelos e documentos vinculados a esta secretaria na fase atual.</p></div><span class="secretaria-doc-group-badge"><?=count($sec['items'])?> documento(s)</span></div><table class="doc-table grouped-doc-table secretaria-grouped-doc-table"><thead><tr><th>Entregas por secretaria</th><th>Modelo único</th><th>Documento</th></tr></thead><tbody>
<?php foreach($sec['items'] as$item):$g=$item['group'];$e=$item['delivery'];$r=$e['requisito'];$d=$e['documento'];$model=$g['modelo'];$approved=$e['classe']==='approved';$canSend=!$faseFormalmenteEncerrada&&(($scope==='stratelli'&&$r['perfil_envio']==='STRATELLI')||($scope!=='stratelli'&&$r['perfil_envio']==='MUNICIPIO'));?>
<tr class="<?=$approved?'row-approved':''?>"><td data-label="Entregas por secretaria"><article class="grouped-delivery-card <?=Format::h($e['classe'])?>"><div class="grouped-delivery-head"><div><strong><?=Format::h($r['secretaria_nome'])?></strong><?php if($r['departamento_nome']):?><small><?=Format::h($r['departamento_nome'])?></small><?php endif;?></div><span class="pill <?=Format::h($e['classe'])?>"><?=Format::h($e['rotulo'])?></span></div><?php if($d):?><div class="grouped-delivery-file audit-aware"><b>Versão <?=Format::h($d['versao'])?></b> · <?=Format::h($d['arquivo_original'])?><br><small>Enviado em <?=Format::h(Format::dateTime($d['enviado_em']))?><?php if(!empty($d['enviado_por_nome'])):?> por <?=Format::h($d['enviado_por_nome'])?><?php endif;?></small><div class="document-integrity-mini"><span><?=Format::h($d['mime_type']?:'MIME não identificado')?></span><span><?=Format::h(Format::fileSize((int)$d['tamanho']))?></span><?php if(!empty($d['checksum_sha256'])):?><span title="<?=Format::h($d['checksum_sha256'])?>">SHA-256 <?=Format::h(substr($d['checksum_sha256'],0,12))?>…</span><?php endif;?></div><?php if(!empty($d['observacao_envio'])):?><small class="document-send-note"><b>Observação do envio:</b> <?=Format::h($d['observacao_envio'])?></small><?php endif;?></div><?php else:?><div class="grouped-delivery-file empty">Nenhum arquivo enviado por esta secretaria.</div><?php endif;?><?php if($d&&$d['status']==='CORRECAO'):?><div class="grouped-delivery-correction"><b>Correção solicitada:</b> <?=Format::h($d['observacao_validacao']?:'Ajustar e reenviar o documento.')?></div><?php endif;?>
<div class="grouped-delivery-actions"><?php if($d):?><a class="btn neutral download-current" href="/<?=Format::h($slug)?>/arquivos/documentos/<?=$d['id']?>">⬇ Baixar enviado</a><?php endif;?><a class="btn neutral document-audit-link" href="/<?=Format::h($slug)?>/documentos/<?=$r['id']?>/auditoria">⌁ Auditoria</a><?php if($canSend):?><form class="upload-form audited-upload-form" method="post" enctype="multipart/form-data" action="/<?=Format::h($slug)?>/workflow/documentos/<?=$r['id']?>/enviar"><input type="hidden" name="_token" value="<?=Format::h(Csrf::token())?>"><input type="hidden" name="fase_id" value="<?=$atividade['id']?>"><label class="audited-upload-field audited-upload-file"><span>Arquivo para envio</span><input type="file" name="arquivo" required></label><label class="audited-upload-field audited-upload-note"><span>Observação do envio <em><?=$obsEnvioObrigatoria?'(obrigatória)':'(opcional)'?></em></span><input class="upload-observation" type="text" name="observacao_envio" maxlength="500" <?=$obsEnvioObrigatoria?'required':''?> placeholder="Ex.: versão revisada conforme orientação"></label><button class="btn primary audited-upload-submit"><?=$d?'Reenviar':'Enviar'?></button></form><?php endif;?></div>
<?php if($isPlatform&&!$faseFormalmenteEncerrada&&$r['perfil_envio']==='MUNICIPIO'&&$d&&$d['status']==='AGUARDANDO'):?><form class="validation grouped-validation" method="post" action="/<?=Format::h($slug)?>/workflow/documentos/<?=$d['id']?>/validar"><input type="hidden" name="_token" value="<?=Format::h(Csrf::token())?>"><input type="hidden" name="fase_id" value="<?=$atividade['id']?>"><textarea name="observacao" rows="2" placeholder="<?=$obsAprovacaoObrigatoria?'Observação obrigatória para aprovar; motivo obrigatório para correção':'Motivo da correção ou observação da aprovação'?>"></textarea><div class="validation-actions"><button class="btn approve" name="validacao" value="aprovar">Aprovar</button><button class="btn correct" name="validacao" value="corrigir">Correção</button></div></form><?php elseif($isPlatform&&$d&&$d['status']==='APROVADO'):?><div class="validation-completed"><span>Validação concluída em <?=Format::h(Format::dateTime($d['validado_em']))?></span><b>✓ APROVADO</b></div><?php endif;?></article></td>
<td data-label="Modelo único"><?php if($model):?><div class="model-box"><a class="btn model" href="/<?=Format::h($slug)?>/arquivos/modelos/<?=$model['id']?>">⬇ Baixar modelo</a><span class="model-meta"><?=Format::h($model['modelo_nome'])?><?php if($model['modelo_tamanho']):?> · <?=Format::h(Format::fileSize((int)$model['modelo_tamanho']))?><?php endif;?><br>Atualizado em <?=Format::h(Format::dateTime($model['modelo_data']))?><br><b>Modelo compartilhado entre as secretarias vinculadas a este documento.</b></span></div><?php else:?><span class="model-empty">Modelo ainda não disponibilizado para este documento.</span><?php endif;?><?php if($isPlatform&&!$faseFormalmenteEncerrada&&!$approved):?><form class="model-upload grouped-model-upload" method="post" enctype="multipart/form-data" action="/<?=Format::h($slug)?>/workflow/modelos/<?=$r['id']?>/enviar"><input type="hidden" name="_token" value="<?=Format::h(Csrf::token())?>"><input type="hidden" name="fase_id" value="<?=$atividade['id']?>"><input type="hidden" name="requisito_ids" value="<?=Format::h($g['ids'])?>"><input type="file" name="arquivo_modelo" required><button class="btn model-upload-btn"><?=$model?'Substituir para todas':'Subir para todas'?></button><small>O arquivo será vinculado a todas as secretarias deste documento.</small></form><?php endif;?></td>
<td data-label="Documento"><div class="grouped-document-title"><b><?=Format::h($r['nome'])?></b><span class="pill <?=Format::h($e['classe'])?>"><?=Format::h($e['rotulo'])?></span></div><?php if($r['descricao']):?><small class="grouped-document-description"><?=Format::h($r['descricao'])?></small><?php endif;?><div class="doc-owner"><span><?=Format::h($r['tipo_nome'])?></span><span class="profile">Envio: <?=Format::h($r['perfil_envio'])?></span><span><?=count($g['entregas'])?> secretaria(s)/unidade(s) vinculada(s)</span><?php if(!$r['obrigatorio']):?><span>Opcional</span><?php endif;?></div></td></tr>
<?php endforeach;?></tbody></table></section><?php endforeach;?></div><?php endif;?></section>

<section class="card delivery-overview-card"><div class="delivery-overview-head"><div><h2>Situação dos documentos da Fase <?=Format::h($atividade['ordem'])?></h2><p>Visão rápida do que foi aprovado, do que aguarda validação, do que precisa de correção e do que ainda falta ser enviado.</p></div><div class="delivery-overview-summary"><div class="delivery-summary-box delivered"><span class="delivery-summary-icon">✓</span><strong><?=$summary['delivered']?></strong><small>Entregues</small></div><div class="delivery-summary-box awaiting-validation"><span class="delivery-summary-icon">…</span><strong><?=$summary['awaiting_validation']?></strong><small>Aguardando validação</small></div><div class="delivery-summary-box needs-correction"><span class="delivery-summary-icon">!</span><strong><?=$summary['needs_correction']?></strong><small>Em correção</small></div><div class="delivery-summary-box not-delivered"><span class="delivery-summary-icon">×</span><strong><?=$summary['not_delivered']?></strong><small>Não entregues</small></div></div></div>
<?php if($summary['total']):?><div class="delivery-progress-bar"><?php if($summary['delivered']):?><span class="delivered" style="width:<?=$summary['percent_delivered']?>%"><b><?=round($summary['percent_delivered'])?>%</b></span><?php endif;?><?php if($summary['awaiting_validation']):?><span class="awaiting-validation" style="width:<?=$summary['percent_waiting']?>%"><b><?=round($summary['percent_waiting'])?>%</b></span><?php endif;?><?php if($summary['needs_correction']):?><span class="needs-correction" style="width:<?=$summary['percent_correction']?>%"><b><?=round($summary['percent_correction'])?>%</b></span><?php endif;?><?php if($summary['not_delivered']):?><span class="not-delivered" style="width:<?=$summary['percent_pending']?>%"><b><?=round($summary['percent_pending'])?>%</b></span><?php endif;?></div><div class="delivery-legend"><span><i class="delivered"></i>Verde: entregue e aprovado</span><span><i class="awaiting-validation"></i>Azul: aguardando validação</span><span><i class="needs-correction"></i>Amarelo: correção necessária</span><span><i class="not-delivered"></i>Vermelho: ainda não entregue</span></div><?php endif;?>
<div class="delivery-secretaria-head"><div><h3><?=$scope==='secretaria'?'Pendências da sua secretaria':'Secretarias com pendências nesta fase'?></h3><p>Lista das ações de envio ou correção ainda necessárias.</p></div><span class="delivery-secretaria-badge"><?=count($secretariasPendentesFase)?> secretaria(s) com pendência</span></div><?php if($secretariasPendentesFase):?><div class="delivery-secretaria-quickgrid"><?php foreach($secretariasPendentesFase as$s):?><article class="delivery-secretaria-quickcard <?=Format::h($s['status_visual'])?>"><div class="delivery-secretaria-quickicon"><?=$s['not_delivered']?'✕':'!'?></div><div class="delivery-secretaria-quickcontent"><div class="delivery-secretaria-quicktop"><strong><?=Format::h($s['nome'])?></strong><span class="delivery-secretaria-quickpill"><?=Format::h($s['rotulo'])?></span></div><div class="delivery-secretaria-quickmeta"><span>× <?=$s['not_delivered']?> pendente(s)</span><span>! <?=$s['needs_correction']?> correção(ões)</span><span>… <?=$s['awaiting_validation']?> aguardando validação</span><span>✓ <?=$s['delivered']?> entregue(s)</span></div></div></article><?php endforeach;?></div><?php else:?><div class="delivery-secretaria-empty">Não há ações de envio ou correção pendentes.</div><?php endif;?>
<div class="delivery-document-grid"><?php foreach($resumoEntregasFase as$item):$r=$item['requisito'];$d=$item['documento'];?><article class="delivery-document-item <?=Format::h($item['status_visual'])?>"><div class="delivery-document-icon"><?=Format::h($item['icone'])?></div><div class="delivery-document-content"><div class="delivery-document-title"><strong><?=Format::h($r['nome'])?></strong><span class="delivery-status-label"><?=Format::h($item['rotulo'])?></span></div><div class="delivery-document-meta"><span><?=Format::h($r['secretaria_nome'])?></span><?php if($r['departamento_nome']):?><span><?=Format::h($r['departamento_nome'])?></span><?php endif;?><span><?=Format::h($r['tipo_nome'])?></span></div><?php if($d&&$d['status']==='APROVADO'):?><p class="delivery-document-detail"><strong>Arquivo aprovado:</strong> <?=Format::h($d['arquivo_original'])?> · versão <?=Format::h($d['versao'])?> · aprovado em <?=Format::h(Format::dateTime($d['validado_em']?:$d['enviado_em']))?></p><?php elseif($d&&$d['status']==='AGUARDANDO'):?><p class="delivery-document-detail"><strong>Arquivo enviado:</strong> <?=Format::h($d['arquivo_original'])?> · versão <?=Format::h($d['versao'])?> · aguardando validação desde <?=Format::h(Format::dateTime($d['enviado_em']))?></p><?php elseif($d):?><p class="delivery-document-detail"><strong>Correção solicitada:</strong> <?=Format::h($d['observacao_validacao']?:'O documento precisa ser ajustado e reenviado.')?></p><?php else:?><p class="delivery-document-detail">Aguardando o envio deste documento.</p><?php endif;?></div></article><?php endforeach;?></div></section>

<section class="card workflow-log-card"><div class="workflow-log-head"><div><h2>Log de documentos da Fase <?=Format::h($atividade['ordem'])?></h2><p>Histórico de modelos, uploads, substituições, aprovações e correções.</p></div><span class="workflow-log-count"><?=$totalLogsFase?> registro(s)</span></div><?php if($historicoFasePagina):?><div class="table-scroll"><table class="workflow-log-table"><thead><tr><th>Data</th><th>Evento</th><th>Documento</th><th>Responsável</th><th>Detalhamento</th></tr></thead><tbody><?php foreach($historicoFasePagina as$h):?><tr><td><?=Format::h(Format::dateTime($h['criado_em']))?></td><td><b><?=Format::h($h['evento'])?></b></td><td><?=Format::h($h['documento']?:$h['arquivo_original'])?></td><td><?=Format::h($h['usuario_nome']?:'Sistema')?></td><td><?=Format::h($h['motivo']?:'—')?><?php if(!empty($h['checksum_sha256'])):?><br><small class="audit-hash-inline">v<?=Format::h($h['versao']?:'—')?> · <?=Format::h($h['mime_type']?:'arquivo')?> · SHA-256 <?=Format::h(substr($h['checksum_sha256'],0,12))?>…</small><?php endif;?></td></tr><?php endforeach;?></tbody></table></div><?php if($totalPaginasLog>1):?><div class="history-pagination"><span>Página <?=$paginaLog?> de <?=$totalPaginasLog?></span><div><?php for($p=1;$p<=$totalPaginasLog;$p++):?><a class="history-page-link <?=$p===$paginaLog?'active':''?>" href="/<?=Format::h($slug)?>/workflow/fase/<?=$atividade['id']?>?log_pagina=<?=$p?>"><?=$p?></a><?php endfor;?></div></div><?php endif;?><?php else:?><div class="empty-state">Nenhuma movimentação registrada nesta fase.</div><?php endif;?></section>
</div>
<?php endif;?>
<?php endif;?>
